
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "'M3*\x95F\xbc\x19$\x9f\xcd#\xf7\xbdx\x94"
    
_lr_action_items = {'AND':([2,3,4,7,8,9,],[5,-4,5,-1,5,5,]),'RPAREN':([3,4,7,8,9,],[-4,7,-1,-2,-3,]),'LPAREN':([0,1,5,6,],[1,1,1,1,]),'OR':([2,3,4,7,8,9,],[6,-4,6,-1,6,6,]),'CARD':([0,1,5,6,],[3,3,3,3,]),'$end':([2,3,7,8,9,],[0,-4,-1,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,5,6,],[2,4,8,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_lparen_expression_rparen','/Users/igor/src/netrunner_utils/card_expression.py',31),
  ('expression -> expression AND expression','expression',3,'p_expression_and_expression','/Users/igor/src/netrunner_utils/card_expression.py',35),
  ('expression -> expression OR expression','expression',3,'p_expression_or_expression','/Users/igor/src/netrunner_utils/card_expression.py',42),
  ('expression -> CARD','expression',1,'p_card','/Users/igor/src/netrunner_utils/card_expression.py',51),
]
